### PR TITLE
Update requirements.txt to add onnxruntime-gpu

### PR DESCRIPTION
**Pull request by sophies927**
## Describe your changes
Added onnxruntime-gpu to requirements.txt since it was not included before and caused an error

## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [ ] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [ ] Lint and apply fixes to your code by running `lintrunner -a`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.
- [ ] Is this PR including examples changes? If yes, please remember to update [example documentation](https://github.com/microsoft/Olive/blob/main/docs/source/examples.md) in a follow-up PR.

### CODE REVIEW

**Comment by trajepl** [comment]
The linter enforce the packages are ordered with alphabetical. Please insert the `onnxruntime-gpu` after `onnxruntime-externsions`

**Comment by trajepl** [comment]
```txt
datasets
neural-compressor>=2.4.1
onnxruntime-extensions
onnxruntime-gpu
# optimum 1.17.0 for fp16 inference
optimum>=1.17.0

```

**Comment by xiaoyu-work** [comment]
I'm okay with this change for now, but ideally onnxruntime is the dependency of Olive rather this example. User should install onnxruntime or run `--setup` to install it. The script of this example doesn't have that step.

**Review by trajepl — APPROVED** [review]

**Pull request merged**
