### PR TITLE
Fix llama2 tensor parallel implementation to work with transformers>=4.36.0

### PR DESCRIPTION
**Pull request by shaahji**
## Describe your changes

Fix llama2 tensor parallel implementation to work with transformers>=4.36.0

## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [x] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [x] Lint and apply fixes to your code by running `lintrunner -a`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.

### CODE REVIEW

**Comment by trajepl** [comment]
Double check: is this change backward compatible with the transformers <4.36.0?

**Comment by shaahji** [comment]
> Double check: is this change backward compatible with the transformers <4.36.0?

I don't see any reason why the change wouldn't be backward compatible. Did something specific stand out to you?

**Comment by trajepl** [comment]
Nothing special, just double check. I saw your PR title contains 'transformers>=4.36.0', and I just do now know what kind of changes in 'transformers>=4.36.0' which are blocking main branch now.

Previously, I updated the whisper model since the transformers 4.36.0 introduce the new interface for model loading. 
https://github.com/microsoft/Olive/pull/802

**Comment by shaahji** [comment]
> Nothing special, just double check. I saw your PR title contains 'transformers>=4.36.0', and I just do now know what kind of changes in 'transformers>=4.36.0' which are blocking main branch now.
> 
> Previously, I updated the whisper model since the transformers 4.36.0 introduce the new interface for model loading. #802

Verified with transformers==4.33.1

**Review by trajepl — APPROVED** [review]

**Pull request merged**
