### PR TITLE
Enable more linter in adapter config

### PR DESCRIPTION
**Pull request by guotuofeng**
## Describe your changes
Enable the following linters
* mypy
* noqa
* space
* tab
* toml-sort
## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [ ] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [ ] Format your code by running `pre-commit run --all-files`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.

### CODE REVIEW

**Comment by trajepl** [comment]
Could you help give a few short introductions about what kinds of linter you enabled? It might be helpful for us to write code as an reference.

**Comment by guotuofeng** [comment]
> Could you help give a few short introductions about what kinds of linter you enabled? It might be helpful for us to write code as an reference.

done

**Review by trajepl — APPROVED** [review]

**Comment by xiaoyu-work** [comment]
Do we still need `pre-commit` check?

**Comment by guotuofeng** [comment]
> Do we still need `pre-commit` check?

The end-of-line fixer is not in linter. So from the time being, we'd better keep pre-commit until we find replacement.

**Comment by justinchuby** [comment]
FYI the end-of-line check can be enabled via editorconfig. Ref

https://github.com/microsoft/onnxscript/blob/21879738d2c07eb7d56a4eb449432e18d3fabe8d/.lintrunner.toml#L134-L157

and 

https://github.com/microsoft/onnxscript/blob/main/.editorconfig

**Pull request merged**
