### PR TITLE
Mention `lintrunner` in the PR checklist

### PR DESCRIPTION
**Pull request by justinchuby**
## Describe your changes

Update the PR checklist to reference `lintrunner` over pre-commit.

### CODE REVIEW

**Comment by justinchuby** [comment]
cc @guotuofeng

**Review by guotuofeng — APPROVED** [review]

**Comment by justinchuby** [comment]
Please feel free to merge as I don't have merge permission

**Comment by guotuofeng** [comment]
> /azp run

Please hold on the PR merge until the fork PR is allowed to enable CI pipelines

**Pull request merged**
