### PR TITLE
Fix inc quantization pass bug

### PR DESCRIPTION
**Pull request by xiaoyu-work**
## Describe your changes
Fix inc quantization pass bug
## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [ ] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [ ] Format your code by running `pre-commit run --all-files`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.

### CODE REVIEW

**Comment by guotuofeng** [comment]
would you please help add more description to clarify what's the bug?

**Comment by trajepl** [comment]
Seems like the bug is invalid arguments from previous changes on `data_root`. The fix is ok for me.
Furthermore we should cover it in our test.

**Comment by xiaoyu-work** [comment]
> would you please help add more description to clarify what's the bug?

The recent change for data_root was added to `evaluator.evaluate()` but inc quantization pass wasn't updated with this change..

**Comment by xiaoyu-work** [comment]
> Seems like the bug is invalid arguments from previous changes on `data_root`. The fix is ok for me. Furthermore we should cover it in our test.

Yeah I was thinking cover more examples in a different pipeline so we can make sure all examples work.

**Review by guotuofeng — APPROVED** [review]

**Pull request merged**
