### PR TITLE
Fix SDXL optimization for DirectML

### PR DESCRIPTION
**Pull request by thevishalagarwal**
Issue: SD XL optimization for DirectML doesn't work due to incorrect config

### CODE REVIEW

**Review by jambayk — APPROVED** [review]
Thanks for the fix! We tested the stable diffusion example in the CI but not this one since the model to too large.

**Comment by Kotomi-Du** [comment]
Hi, @thevishalagarwal 
May I ask what kind of optimization it does for SDXL? I have tried to convert a new optimized model based on latest commit, but didn't see the performance improve for unet on NV4060ti and Intel discrete graphics.

**Comment by thevishalagarwal** [comment]
@Kotomi-Du For SDXL 1.0 base, I can see the number of nodes reduced from 15345 to 3322 and a magnitude of reduced inference time.

**Pull request merged**
