### PR TITLE
enable diagnosis for inc quantization

### PR DESCRIPTION
**Pull request by guotuofeng**
## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [ ] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [ ] Lint and apply fixes to your code by running `lintrunner -a`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.

### CODE REVIEW

**Comment by guotuofeng** [comment]
@yuwenzho, would you please help take a look?

**Comment by yuwenzho** [comment]
> @yuwenzho, would you please help take a look?

`diagnosis` mode in INC is only available for static quantization for ONNXRuntime now.

**Comment by guotuofeng** [comment]
> he purpose of `diagnosis` mode is to provide a way to debug precision loss during quantization.

just enable diagnosis for static quantization.

**Review by yuwenzho — CHANGES_REQUESTED** [review]
Add dataloader assert if diagnosis is true.

**Review by trajepl — APPROVED** [review]

**Comment by guotuofeng** [comment]
> Add dataloader assert if diagnosis is true.

just add the assert

**Review by yuwenzho — APPROVED** [review]

**Review by trajepl — APPROVED** [review]

**Pull request merged**
